version: '3.8'

services:
  backend:
    build: ./backend
    # --workers provides a single worker process
    # the host defines the address to host the server on and port defines the port to hose the server on
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      # Reminder: <host-port>:<container-port>
      - 8004:8000
    environment:
      - ENVIRONMENT=production
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/test
    depends_on:
      - db

  db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  frontend:
    image: docker-nextjs
    build:
      dockerfile: ./frontend/Dockerfile.production
    ports:
      - '3000:3000'
